platform :ios, '14.0'

target 'GMGit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMGit
  pod 'Alamofire', '~> 4.9.1'

  target 'GMGitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GMGitUITests' do
    # Pods for testing
  end

end
